### ISSUE TITLE
DSC extension is not correctly importing SAS token after initial deployment

### ISSUE THREAD

**Issue by artisticcheese** [PowerShell/PowerShell-Blog-Samples#3]
Having the same issue as the guy commented on the thread (https://blogs.msdn.microsoft.com/powershell/2015/10/21/azure-dsc-extension-2-8-how-to-map-downloads-of-the-extension-dependencies-to-your-own-location/) that any new deployments of virtual machines are inheriting old SAS token which is not valid anymore and hence DSC procurement fails.
```
18:24:02 - 6:24:01 PM - VM has reported a failure when processing extension 'Microsoft.Powershell.DSC'. Error message: "The DSC Extension failed to execute: Error downloading https://cs77d0ba820d01cx4b11xae4.blob.core.windows.net/swarmhosts-rg-stageartifacts/DSC/DSC.zip after 2 attempts: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:da36df94-001e-011a-7579-392a09000000
Time:2017-09-29T23:23:10.9046779Z</Message><AuthenticationErrorDetail>Signed expiry time [Mon, 25 Sep 2017 23:54:42 GMT] must be after signed start time [Fri, 29 Sep 2017 23:23:10 GMT]</AuthenticationErrorDetail></Error>.
```

**Comment by denisbuco** [comment]
Any solution regading this?

**Comment by artisticcheese** [comment]
I modified template to increase lifetime of SAS token to maximum. It's not a solution but workaround.

**Comment by denisbuco** [comment]
Could you give me some guidance, where I've to change it?

**Comment by artisticcheese** [comment]
In your `Deploy-AzureResourceGroup.ps1` file in VS find a line which creates SASToken and add -ExpiryTime parameter like below
`New-AzureStorageContainerSASToken -Container $StorageContainerName -Context $StorageAccount.Context -Permission r -ExpiryTime (Get-Date).AddYears(10) -Verbose`
